### ISSUE TITLE
propagation of @since annotations

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2-apidoc#137]
Currently `@since` annotations are not propageted via `@inheritdoc` and are also not propagated to properties added by getters and setters.

**Comment by brandonkelly** [comment]
A subclass with `@inheritdoc` could belong to a different library, in which case you wouldn’t want it to inherit the `@since` tag.

How should we tell the difference? Maybe look up the location of the original class, and compare it to the subclass’ location? And accept it if they are within the same `vendor/x/y/` folder?

**Comment by brandonkelly** [comment]
Submitted #190 with that `vendor/` based approach.
