### ISSUE TITLE
Is it possible to upgrade nikic/php-parser to 2.x or 3.x?

### ISSUE THREAD

**Issue by yyxx9988** [yiisoft/yii2-apidoc#146]
1.x is too low for other dependencies of my project

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11
| PHP version      | 7.0.11
| Operating system | Linux

**Comment by cebe** [comment]
need to check compatibility, but it should be possible.

**Comment by markch123** [comment]
Im not sure when 2.1.1 is scheduled to be released, but if its next year would it be possible to have a look at this for 2..0.X ?  PHP 7.2 will be released later this year, which means we'll probably be now 3 versions behind (if we assume nikic/php-parser v4 will come up for 7.2).

**Comment by frontbear** [comment]
nikic/php-parser v4.0 released.

https://github.com/nikic/PHP-Parser/releases/tag/v4.0.0

**Comment by cebe** [comment]
note to myself:
- https://twitter.com/Ocramius/status/994645082438623237 
- https://andreas.heigl.org/2018/04/09/scoping-phar-files/

**Comment by samdark** [comment]
phpdocumentor/reflection 3.0.1 requires nikic/php-parser ^1.0 and that's the only non-beta version and the only version that still runs PHP 5. phpdocumentor/reflection 4 is still beta and needs nikic/php-parser 4 along with PHP 7.1+.

So either we raise minimum requirements to PHP 7.1 or there's no update.

**Comment by markch123** [comment]
Maybe just upgrade phpdocumentor/reflection  to 4,  nikic/php-parser  to 4.2 and state PHP 7.2 as min level for yii2-apidoc?

The developer states "composer require "phpdocumentor/reflection: ~4.0" in their installation instructions so I would think many people have been using it for a while.

Is it a big deal have different PHP version support between different yii products? Not really as I already have to run an alternate version to run yii-apidoc anyway.

**Comment by nagyt234** [comment]
I just started to work with yii2-apidoc and I get a lot of parse error, because using semi-reserved words as constants. S. PHP doc: ["As of PHP 7.0.0 these keywords are allowed as property, constant, and method names of classes, interfaces and traits, except that class may not be used as constant name."](https://www.php.net/manual/en/reserved.keywords.php). That was already solved in nikic/php-parser 2.0.1.

Realy nikic/php-parser 1.4.1 is more than 4 years old. There are a lot of bug fix in the newer versions. The current version is 4.3.1.

I would release a new version of yii2-apidoc with PHP 7.1+. Everybody who is using older PHP could still work with the older yii2-apidoc, as mentioned by @markch123.

**Comment by samdark** [comment]
@nagyt234 do you want to work on adjusting the codebase to work with it?

**Comment by nagyt234** [comment]
@samdark OK, I'm starting to work on it in my spare time.

**Comment by nagyt234** [comment]
@samdark I'm sorry. It's much more complicated than I thought. phpDocumentor/Reflection is documented very pourly and it was totally changed. I can not do it. I have to unassign me.

**Comment by samdark** [comment]
OK.
